name: mebt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.3
  csv: ^5.0.0
  path_provider: ^2.1.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/retailers.csv
